version: '2'

services:
  node0:
    container_name: node0
    build: ./cfg/testnet/
    ports:
      - "5050:5050"
      - "5020:5020"
    volumes:
      - ./:/root
    command: /bin/bash -c 'cd /root/ && ./build/call --start --conf ./cfg/testnet/calld.node0.cfg -q'
    networks:
      localnet:
        ipv4_address: 192.168.20.2

  node1:
    container_name: node1
    build: ./cfg/testnet/
    volumes:
      - ./:/root
    depends_on: 
      - node0
    command: /bin/bash -c 'cd /root/ && ./build/call --net --conf ./cfg/testnet/calld.node1.cfg -q'
    networks:
      localnet:
        ipv4_address: 192.168.20.3

  node2:
    container_name: node2
    build: ./cfg/testnet/
    volumes:
      - ./:/root
    depends_on: 
      - node0
    command: /bin/bash -c 'cd /root/ && ./build/call --net --conf ./cfg/testnet/calld.node2.cfg -q'
    networks:
      localnet:
        ipv4_address: 192.168.20.4

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: 192.168.20.0/16
