FROM ubuntu
MAINTAINER Torrie Fischer <torrie@call.com>

RUN apt-get update -qq &&\
    apt-get install -qq software-properties-common &&\
    apt-add-repository -y ppa:ubuntu-toolchain-r/test &&\
    apt-add-repository -y ppa:afrank/boost &&\
    apt-get update -qq

RUN apt-get purge -qq libboost1.48-dev &&\
    apt-get install -qq libprotobuf8 libboost1.57-all-dev

RUN mkdir -p /srv/calld/data

VOLUME /srv/calld/data/

ENTRYPOINT ["/srv/calld/bin/calld"]
CMD ["--conf", "/srv/calld/data/calld.cfg"]
EXPOSE 51235/udp
EXPOSE 5005/tcp

ADD ./calld.cfg /srv/calld/data/calld.cfg
ADD ./calld /srv/calld/bin/
